#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include "double.h"
#include "matrix_sparse.h"
#include "mesh_qc.h"

/*
Let:
  . X be the interior of unit square, S be its boundary;
  . f: X -> R be the constant function -4;
  . g_d: S -> R be defined by g_d(x, y) = x^2 + y^2.
Consider the problem of finding u: X -> R such that
  . -\Delta u = f on X
  . u(x, y) = g_d(x, y) on S
This problem has unique solution
  u(x, y) = x^2 + y^2.
The following program finds an approximate solution on a mesh which is a Forman
subdivision of of an initial mesh M, using the discrete Laplacian generated by
some inner product.
I suggest using the one in \cite{berbatov2023discrete} on page 19,
Equation 2.90.
*/

static double f(const double * x)
{
  return - 4;
}

static double g_d(const double * x)
{
  return x[0] * x[0] + x[1] * x[1];
}

int main(int argc, char ** argv)
{
  char * m_format, * m_laplacian_0_format, * m_laplacian_0_name, * m_name,
       * out_format;
  double * x;
  mesh * m;
  jagged1 * m_nodes_bd;
  matrix_sparse * m_laplacian_0;

  if (argc != 6)
  {
    errno = EINVAL;
    fputs("main - the number of command-line arguments must be 6\n", stderr);
    goto end;
  }

  m_name = argv[1];
  m_format = argv[2];
  m = mesh_file_scan_by_name(m_name, m_format);
  if (errno)
  {
    fputs("main - cannot scan m\n", stderr);
    goto end;
  }

  m->fc = mesh_fc(m);
  if (errno)
  {
    fputs("main - cannot calculate m->fc\n", stderr);
    goto m_free;
  }

  m_nodes_bd = mesh_boundary_nodes(m);
  if (errno)
  {
    fputs("main - cannot calculate m_nodes_bd\n", stderr);
    goto m_free;
  }

  m_laplacian_0_name = argv[3];
  m_laplacian_0_format = argv[4];

  m_laplacian_0 =
    matrix_sparse_file_scan_by_name(m_laplacian_0_name, m_laplacian_0_format);
  if (errno)
  {
    fputs("main - cannot calculate m_laplacian[0]\n", stderr);
    goto m_nodes_bd_free;
  }

  x = matrix_sparse_laplace_equation_solve(
    m_laplacian_0, m->dim_embedded, m->coord, m_nodes_bd, f, g_d);
  if (errno)
  {
    fputs("main - cannot calculate x\n", stderr);
    goto m_laplacian_0_free;
  }

  // {
  //   int i;
  //   double error;
  //   for (i = 0; i < m_laplacian_0->rows; ++i)
  //   {
  //     error = x[i] - g_d(m->coord + m->dim_embedded * i);
  //     fprintf(stderr, "%g\n", error);
  //   }
  // }

  out_format = argv[5];
  double_array_file_print(stdout, m_laplacian_0->rows, x, out_format);

  free(x);
m_laplacian_0_free:
  matrix_sparse_free(m_laplacian_0);
m_nodes_bd_free:
  jagged1_free(m_nodes_bd);
m_free:
  mesh_free(m);
end:
  return errno;
}
